name: Build AdvancedTimeIsland

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: AdvancedTimeIsland.sln
      Project_Path: AdvancedTimeIsland.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build the project
      run: dotnet build $env:Project_Path --configuration Release --no-restore

    - name: Create .cipx package
      run: .\Build-Package.ps1

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Output
        path: bin/Release/net8.0-windows/

    - name: Upload .cipx package
      uses: actions/upload-artifact@v4
      with:
        name: AdvancedTimeIsland.cipx
        path: bin/Release/net8.0-windows/AdvancedTimeIsland.cipx